//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerDeneme2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tonerler
    {
        public int Id { get; set; }
        public string MarkaAdi { get; set; }
        public string Model { get; set; }
        public Nullable<double> Stok { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
