//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LoginUser
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Lütfen kullanıcı adını giriniz.")]
        [Display(Name = "Username")]

        public string Username { get; set; }
        [Required(ErrorMessage = "Lütfen şifre giriniz.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string PasswordUs { get; set; }

        [Required(ErrorMessage = "Lütfen şifreyi tekrar giriniz.")]
        [Display(Name = "RePassword")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("PasswordUs", ErrorMessage = "Şifreler eşleşmiyor, lütfen tekrar giriniz!")]
        public string RePasswordUs { get; set; }
    }
}
