//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Urunler
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Ürün adını giriniz!")]
        [Display(Name ="Ürün Adı")]
        public string UrunAdi { get; set; }
        [Display(Name = "Açıklama")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Stok adetini giriniz!")]
        [Display(Name = "Stok")]
        public Nullable<double> Stok { get; set; }
        public Nullable<double> StokTemp { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
